name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup uv package manager
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Setup Node
        uses: actions/setup-node@v6

      - name: Install semantic-release
        run: npm install

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
